---
- name: Setup Terraform on New Ubuntxu 20.04 System
  hosts: localhost
  gather_facts: true
  tasks:

    - block:
        - name: Update the APT Package Cache
          become: true
          apt:
            update_cache: true
            cache_valid_time: 3600
        - name: Add Hashicorp signing key
          become: true
          apt_key:
            url: "https://apt.releases.hashicorp.com/gpg"
            state: present
      when:
        - ansible_os_family == "Debian"
        - ansible_os_family == "CentOS"
    
    
    # - name: Add the Hashicorp Repo to Ubuntu
    #   become: true
    #   apt_repository:
    #     repo: "deb [arch=amd64] https://apt.releases.hashicorp.com focal main"
    #     state: present

    # - name: Install software from standard repos and hashicorp
    #   become: true
    #   package:
    #     name:
    #       - gnupg
    #       - software-properties-common
    #       - curl
    #       - terraform
    