---
- include_tasks: pre_install.yml

- block:
    - include_tasks: uninstall_old_docker_versions.yml
    - include_tasks: system_requirements.yml
    - include_tasks: install_docker_ce.yml
  when:
    - ansible_distribution == "Rocky"
    - ansible_distribution_major_version == "8"
