---
- name: Install epel repo extra packages
  yum:
    name: epel-release
    state: present
  when: ansible_distribution == 'Rocky'

- name: Requirements packages before install docker
  yum:
    name: [
      'yum-utils',
      'device-mapper-persistent-data',
      'lvm2'
    ]
    state: present
    update_cache: yes

- name: Install Extra packages including networking tools
  yum:
    state: present
    name: [
      'vim',
      'tree',
      'nmap',
      'htop',
      'net-tools',
      'telnet',
      'nc',
      'curl',
      'wget',
      'lsof',
      'jq',
      'bind-utils',
      'traceroute',
      'tcpdump',
      'ncdu',
      'bash-completion'
    ]
